misplaced C variable declaration in current code
options.c
..\src\options.c(4072) : error C2275: 'boolean' :
	illegal use of this type as an expression
        c:\personal\nhdev\350\test\include\global.h(56) :
	see declaration of 'boolean'
..\src\options.c(4072) : error C2146: syntax error :
	missing ';' before identifier 'found'
..\src\options.c(4072) : error C2065: 'found' : undeclared identifier
..\src\options.c(4072) : error C2065: 'numeric' : undeclared identifier
..\src\options.c(4077) : error C2065: 'found' : undeclared identifier
..\src\options.c(4088) : error C2065: 'numeric' : undeclared identifier
..\src\options.c(4090) : error C2065: 'found' : undeclared identifier
..\src\options.c(4090) : error C2065: 'numeric' : undeclared identifier